name: XSOAR CI/CD
on:
  pull_request:
    types: [closed, synchronize, opened]
    branches:
        - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CI/CD pull_request checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - name: 
        if: github.event.pull_request.merged == false
        run: |
            pip install demisto_sdk
            python3 -c 'from demisto_sdk.commands.common.tools import get_content_id_set; print(get_content_id_set())'
           
