name: XSOAR CI/CD
on:
  pull_request:
    types: [closed, synchronize, opened]
    branches:
        - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CI/CD pull_request checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - name: 
        if: github.event.pull_request.merged == false
        run: |
            ls -la
            wget https://storage.googleapis.com/marketplace-dist/content/id_set.json -o test.json 
            ls -la
            cat test.json
